function [m2] = seiri_suru(m) % temp

m2 = matfile('ML_input_file3.mat','Writable',true);

valueset = [0 1 2];
catnames = {'0', '1', '2'};

input_name = fieldnames(m);
input_name = input_name{2,1};

[~,S] = size(m,input_name);
for i = 1:S
    
    input = m.(input_name)(1,i);
    
    % MLP
    output.dataMLP =  [input.RRI.RRI_segP;...
        input.RRI.RRI_segWT;...
        input.RRI.RRI_segWU;...
        input.RRI.RRI_segWP;...
        input.RRI.RRI_segJ;...
        input.RRI.RRI_segS;...
        input.RRI.RRI_segE];
    output.labelMLP = input.RRI.RRI_segL;
%     
%     
%     % Deep
%     [N,M] = size(input.RRI.RRI_segP);
%     for j = 1:M
%         
%         output(1,i).dataDEEP{j,1} = [input.RRI.RRI_segP(:,j)';...
%             input.RRI.RRI_segWT(:,j)';...
%             input.RRI.RRI_segWU(:,j)';...
%             input.RRI.RRI_segWP(:,j)';...
%             input.RRI.RRI_segJ(1,j)*ones(1,N);...
%             input.RRI.RRI_segJ(2,j)*ones(1,N);...
%             input.RRI.RRI_segJ(3,j)*ones(1,N);...
%             input.RRI.RRI_segJ(4,j)*ones(1,N);...
%             input.RRI.RRI_segS(1,j)*ones(1,N);...
%             input.RRI.RRI_segS(2,j)*ones(1,N);...
%             input.RRI.RRI_segS(3,j)*ones(1,N);...
%             input.RRI.RRI_segS(4,j)*ones(1,N);...
%             input.RRI.RRI_segE(1,j)*ones(1,N);...
%             input.RRI.RRI_segE(2,j)*ones(1,N);...
%             input.RRI.RRI_segE(3,j)*ones(1,N);...
%             input.RRI.RRI_segE(4,j)*ones(1,N)];
%     end    
%     output(1,i).labelDEEP = [categorical(input.RRI.RRI_segLD(1,:),valueset,catnames)]';
    
%     [N,M,O] = size(input.INT.INT_seg);
%     for j = 1:M
%        output.dataDEEP2{j,1} = [input.INT.INT_seg(:,j,1)'];
%        
% %            [input.INT.INT_segTF_IF(:,j,1)';...
% %            input.INT.INT_segTF_IF(:,j,2)';...
% %            input.INT.INT_segTF_SE(:,j,1)';...
% %            input.INT.INT_segTF_SE(:,j,2)'];
%        
% %            [input.INT.INT_segTF_WS(:,:,j,1)];
% %            input.INT.INT_segTF_WS(:,:,j,2)];          
%     end
%     output.labelDEEP2 = [categorical(input.INT.INT_segLD(1,:),valueset,catnames)]';
%     
    input_name2 = 'ML_input_file';
    m2.(input_name2)(1,i) = output;
    clear input output;    
end

end